# Vulnbox 3 – DVWA
# Damn Vulnerable Web Application (DVWA) is a PHP/MySQL web app designed for security training.
# It contains multiple vulnerabilities of varying difficulty, making it ideal for practice.

FROM vulnerables/web-dvwa

ENV MYSQL_PASS=p@ssw0rd

HOSTNAME vulnbox3

EXPOSE 80 443
